### ISSUE TITLE
USMCkit.sqf

### ISSUE THREAD

**Issue by saunatyyny** [saunatyyny/Preparations.Tanoa#6]
Veneen gear kuntoon

**Comment by zpede** [comment]
Venegearit tehty.

**Comment by NummiE** [comment]
Muutettu MARRECkit.sqf:ksi uusimmassa commitissä. [https://github.com/saunatyyny/Preparations.Tanoa/commit/dd150fe2bce04891fa33f62d49866a03775c9fcb](url)
